name: "Build Artifact"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci

      - name: Package for Chrome
        run: npm run pack:chrome
      - uses: actions/upload-artifact@v3
        with:
          name: TwitchChatMask_chrome
          path: build/chrome-mv3-prod/*

      - name: Package for Firefox
        run: npm run pack:firefox
      - uses: actions/upload-artifact@v3
        with:
          name: TwitchChatMask_firefox
          path: build/firefox-mv3-prod/*
