name: "Build Artifact"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm run build
      - run: npm run pack
      - uses: actions/upload-artifact@v3
        with:
          name: Twitch Chat Mask.zip
          path: build/chrome-mv3-prod.zip
